services:
  redis:
    image: redis
    container_name: redis-container
    networks:
      - default

  matchmaker:
    build:
      context: .
      dockerfile: ./dockerfile
    networks:
      - default